#------------------------------------------------------------------------------
# usage: Use tutor to enable the Open edX Discovery service plugin
#------------------------------------------------------------------------------
name: Open edX Tutor k8s enable Discovery plugin
description: Github Action to install and enable the Tutor plugin - Open edX Discovery service
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  namespace:
    description: 'The Kubernetes namespace to which the Open edX platform environment will be deployed. Example: openedx-prod'
    required: true
    type: string
  tutor-discovery-version:
    description: 'The version of tutor-discovery to install'
    required: false
    default: latest
    type: string
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    # retrieve the MySQL connection parameters that we created in Terraform
    # and then stored in Kubernetes secrets. These include:
    #   MYSQL_HOST: mysql.app.yourdomain.com
    #   MYSQL_PORT: "3306"
    #   OPENEDX_MYSQL_USERNAME: openedx
    #   OPENEDX_MYSQL_PASSWORD: **************
    #   MYSQL_ROOT_USERNAME: root
    #   MYSQL_ROOT_PASSWORD: *************
    #
    # Also note that we are using jq to add a prefix of "TUTOR_" to each of the parameter names
    #
    # see: https://github.com/Medality-Health/openedx_devops/blob/main/terraform/modules/mysql/main.tf

    - name: fetch MySQL configuration from Kubernetes secrets
      id: get-secret
      uses: openedx-actions/tutor-k8s-get-secret@v1.0.0
      with:
        eks-namespace: ${{ inputs.namespace }}
        eks-secret-name: mysql-discovery

    - name: Enable the Discovery plugin
      run: |-
        pip install tutor-discovery${{ inputs.tutor-discovery-version != 'latest' && format('=={0}', inputs.tutor-discovery-version) || '' }}
        tutor plugins enable discovery
        tutor config save
      shell: bash
